### ISSUE TITLE
--force=true does not overwrite migration and db table

### ISSUE THREAD

**Issue by ja-tomasz** [webNeat/lumen-generators#28] opened 2017-02-03 13:17 UTC
If I realize I made a mistake in the model definition and I run resource(s) generator again (--force=true), it creates another migration, with new timestamp and either fails when trying to declare again the migration class with the same name or fails when running the migration, because the table already exists in the db.

Probably this also applies to the model and migration generator.

**Comment by webNeat** [comment] 2017-02-03 15:09
I guess this is duplicate of the [previous issue](https://github.com/webNeat/lumen-generators/issues/27). 
Please refer to it :)

**Closed as completed by webNeat** 2017-02-03 15:09 UTC
Labels: duplicate
