### ISSUE TITLE
"wn:resources filename" may not generate schema if there are dependencies between tables

### ISSUE THREAD

**Issue by bv-vd** [webNeat/lumen-generators#37] opened 2017-06-30 15:12 UTC
# Problem
When putting schema definitions in a YAML file and running `wn:resources yml-file`, errors may occur related to certain tables not existing, if the schema has several tables and there are dependencies between them, e.g. foreign keys etc.

# Possible cause
The sequence of running migration is not as expected. The generated migration files seems to be run in alphabetical order, which may not be the correct order of creating tables.

# Work around
Rename the migration files so that the files are ordered per the sequence of creating tables

# Suggested Fix
Name the migration files per the order in the `yml-file`, so that the tables can be created in the sequence as expected

**Comment by eperazzo** [comment] 2017-07-02 14:45
Regarding the root cause, it seems the problem is that all migrations have the same timestamp of creation, which leads to the files being sorted in alphabetical order based on the suffix.
<p>
Maybe another option to get rid of this issue would be to allow the developer to enter the sequence number of each resource in the file, which could be appended to the timestamp (before the migration name suffix), so it can be properly sorted within the filesystem.

**Comment by josiahdahl** [comment] 2017-08-03 04:08
@eperazzo I ran into this same issue recently when using this library. My idea was to order them by the order that they appear in the yml file, though I like being able to order them yourself.

**Comment by josiahdahl** [comment] 2017-08-08 22:31
@webNeat Please close this issue, as it's been resolved.

**Closed as completed** 2017-08-08 22:58 UTC
